
USE Customer_Behavior;
select*from customer_sales

-- Q1. Total revenue generated by male vs. female customers
SELECT 
    gender,
    SUM([purchase amount (usd)]) AS total_revenue
FROM 
    customer_sales
GROUP BY 
    gender;


-- Q2. Customers who used a discount but spent more than the average purchase amount
SELECT 
    [customer id],
    gender,
    [purchase amount (usd)] AS purchase_amount,
    [discount applied]
FROM 
    customer_sales
WHERE 
    [discount applied] = 'Yes'
    AND [purchase amount (usd)] > (
        SELECT AVG([purchase amount (usd)]) FROM customer_sales
    )
ORDER BY 
    [purchase amount (usd)] DESC;


-- Q3. Which are the top 5 products with the highest average review rating?

-- Q3. Top 5 products with the highest average review rating
SELECT 
    [item purchased] AS product_name,
    ROUND(AVG([review rating]), 2) AS avg_review_rating,
    COUNT(*) AS total_reviews
FROM 
    customer_sales
WHERE 
    [review rating] IS NOT NULL
GROUP BY 
    [item purchased]
ORDER BY 
    avg_review_rating DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping
SELECT 
    [shipping type] AS shipping_method,
    ROUND(AVG([purchase amount (usd)]), 2) AS avg_purchase_amount,
    COUNT(*) AS total_orders
FROM 
    customer_sales
GROUP BY 
    [shipping type]
ORDER BY 
    avg_purchase_amount DESC;


-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    [subscription status] AS subscription_status,
    ROUND(AVG([purchase amount (usd)]), 2) AS avg_purchase_amount,
    SUM([purchase amount (usd)]) AS total_revenue,
    COUNT(*) AS total_orders
FROM 
    customer_sales
GROUP BY 
    [subscription status]
ORDER BY 
    avg_purchase_amount DESC;



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    [item purchased] AS product_name,
    COUNT(CASE WHEN [discount applied] = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage,
    COUNT(*) AS total_purchases,
    COUNT(CASE WHEN [discount applied] = 'Yes' THEN 1 END) AS discounted_purchases
FROM 
    customer_sales
GROUP BY 
    [item purchased]
HAVING 
    COUNT(*) > 0
ORDER BY 
    discount_percentage DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

-- Q7. Segment customers into New, Returning, and Loyal 
-- based on their total number of previous purchases,
-- and show the count of each segment.

SELECT 
    CASE 
        WHEN [previous purchases] = 0 THEN 'New Customer'
        WHEN [previous purchases] BETWEEN 1 AND 5 THEN 'Returning Customer'
        WHEN [previous purchases] > 5 THEN 'Loyal Customer'
        ELSE 'Unknown'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM 
    customer_sales
GROUP BY 
    CASE 
        WHEN [previous purchases] = 0 THEN 'New Customer'
        WHEN [previous purchases] BETWEEN 1 AND 5 THEN 'Returning Customer'
        WHEN [previous purchases] > 5 THEN 'Loyal Customer'
        ELSE 'Unknown'
    END
ORDER BY 
    customer_count DESC;


-- Q8. Top 3 most purchased products within each category (SQL Server version)

WITH RankedProducts AS (
    SELECT 
        category,
        [item purchased] AS product_name,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_within_category
    FROM 
        customer_sales
    GROUP BY 
        category, [item purchased]
)
SELECT 
    category,
    product_name,
    total_purchases
FROM 
    RankedProducts
WHERE 
    rank_within_category <= 3
ORDER BY 
    category, total_purchases DESC;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    CASE 
        WHEN [previous purchases] > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    [subscription status] AS subscription_status,
    COUNT(*) AS customer_count
FROM 
    customer_sales
GROUP BY 
    CASE 
        WHEN [previous purchases] > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END,
    [subscription status]
ORDER BY 
    customer_type, customer_count DESC;


-- Q10. What is the revenue contribution of each age group?

SELECT 
    [Age],
    SUM([purchase amount (usd)]) AS total_revenue,
    ROUND(
        SUM([purchase amount (usd)]) * 100.0 / 
        (SELECT SUM([purchase amount (usd)]) FROM customer_sales), 
    2) AS revenue_percentage
FROM 
    customer_sales
GROUP BY 
    [Age]
ORDER BY 
    total_revenue DESC;
